SELECT G.GIDERAD,G.GIDERACIKLAMA,GT.TURAD,
CONVERT(varchar,SG.GIDERBASLANGIC,4) as BASLANGICTARIH,
CONVERT(varchar,SG.GIDERBITIS,4) as BITISTARIHI,
SG.GIDERTUTAR FROM SGIDER SG
INNER JOIN GIDER G ON G.GIDERID=SG.GIDERID
INNER JOIN GTUR GT ON GT.GTURID=G.GIDERTURU  
select * from SGIDER
declare  @bitis date,  @baslangic date
SET @bitis='30.11.23'
set @baslangic='31.05.24'
SELECT G.GIDERAD, SG.GIDERTUTAR,
CASE 
WHEN SG.GUNLUK=0 THEN DATEDIFF(MONTH,'2023-11-30','2024-05-31')*SG.GIDERTUTAR 
WHEN SG.GUNLUK=1 THEN SG.GIDERTUTAR 
END AS AYARALIGI
FROM SGIDER SG 
                     INNER JOIN GIDER G ON G.GIDERID = SG.GIDERID 
                     WHERE SG.GIDERBASLANGIC <= '2024-05-31' AND SG.GIDERBITIS >='2023-11-30'



					 SELECT * FROM SGIDER